system_name: maicq
seed: 42
wandb_project: og-marl
training_steps: 1e5

task:
  source: og_marl
  env: smac_v1
  scenario: 3m
  dataset: Good

replay:
  sequence_length: 20
  sample_period: 1

system:
  learning_rate: 1e-3
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  mixer_embed_dim: 32
  mixer_hyper_dim: 64
  discount: 0.99
  target_update_period: 200
  add_agent_id_to_obs: True
  icq_advantages_beta: 0.1
  icq_target_q_taken_beta: 1000
