system_name: "maddpg+cql (torch)"
seed: 42
wandb_project: og-marl
training_steps: 5e5

task:
  source: og_marl
  env: gymnasium_mamujoco
  scenario: 2halfcheetah
  dataset: Replay

replay:
  sequence_length: 20
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.005
  critic_learning_rate: 3e-4
  policy_learning_rate: 3e-4
  add_agent_id_to_obs: True
  num_ood_actions: 10
  cql_weight: 2
  cql_sigma: 0.3
  device: cuda

